#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: shreedev44/crud-notification-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
          envFrom:
            - configMapRef:
                name: env-notification-config


---


#Service
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec: 
  type: LoadBalancer
  selector: 
    app: notification
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051